# Generated by Django 4.2.28 on 2026-02-13 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredBoat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sail_number', models.CharField(max_length=20)),
                ('boat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.boattype')),
            ],
        ),
    ]
