# Generated by Django 4.2.28 on 2026-02-14 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('races', '0003_league'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('type', models.CharField(choices=[('race', 'Race'), ('meeting', 'Meeting'), ('workparty', 'Work Party')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('running', 'Running'), ('finished', 'Finished'), ('verified', 'Verified'), ('locked', 'Locked')], default='draft', max_length=20)),
                ('assistant_race_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='races_as_aro', to=settings.AUTH_USER_MODEL)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='races.event')),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='races', to='races.league')),
                ('race_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='races_as_ro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RaceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boat_type_name', models.CharField(max_length=200)),
                ('py_used', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='races.registeredboat')),
                ('crew', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='races_as_crew', to=settings.AUTH_USER_MODEL)),
                ('helm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races_as_helm', to=settings.AUTH_USER_MODEL)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='races.race')),
            ],
        ),
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ok', 'Finished'), ('dnf', 'DNF'), ('dsq', 'DSQ'), ('dns', 'DNS')], default='ok', max_length=10)),
                ('points_override', models.IntegerField(blank=True, null=True)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='races.raceentry')),
            ],
        ),
        migrations.AddConstraint(
            model_name='raceentry',
            constraint=models.UniqueConstraint(fields=('race', 'boat'), name='unique_boat_per_race'),
        ),
        migrations.AddConstraint(
            model_name='raceentry',
            constraint=models.UniqueConstraint(fields=('race', 'helm'), name='unique_helm_per_race'),
        ),
    ]
