# Generated by Django 4.2.28 on 2026-02-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0004_event_race_raceentry_raceresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceentry',
            name='finish_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
