# Generated by Django 4.2.28 on 2026-02-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0006_raceentry_result_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceentry',
            name='elapsed_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='raceentry',
            name='laps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
