# Generated by Django 4.2.28 on 2026-02-16 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0007_raceentry_elapsed_seconds_raceentry_laps'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('sequence', models.IntegerField()),
                ('event_type', models.CharField(max_length=50)),
                ('race_seconds', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='races.race')),
                ('race_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='races.raceentry')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('device_id', 'sequence')},
            },
        ),
    ]
