# Generated by Django 4.2.28 on 2026-02-17 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('races', '0008_raceevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('timed', 'Timed from Event Log'), ('manual_time', 'Manual Laps & Time'), ('manual_position', 'Manual Positions Only')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('saved', 'Saved'), ('published', 'Published')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_sets', to='races.race')),
            ],
        ),
        migrations.CreateModel(
            name='ResultSetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laps', models.IntegerField(blank=True, null=True)),
                ('elapsed_seconds', models.IntegerField(blank=True, null=True)),
                ('finish_position', models.IntegerField(blank=True, null=True)),
                ('corrected_seconds', models.FloatField(blank=True, null=True)),
                ('race_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='races.raceentry')),
                ('result_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='races.resultset')),
            ],
        ),
    ]
