# Generated by Django 4.2.28 on 2026-02-17 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0009_resultset_resultsetentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raceentry',
            name='elapsed_seconds',
        ),
        migrations.RemoveField(
            model_name='raceentry',
            name='finish_position',
        ),
        migrations.RemoveField(
            model_name='raceentry',
            name='laps',
        ),
        migrations.RemoveField(
            model_name='raceentry',
            name='result_status',
        ),
    ]
