# Generated by Django 4.2.28 on 2026-02-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0010_remove_raceentry_elapsed_seconds_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='resultset',
            constraint=models.UniqueConstraint(fields=('race', 'created_by', 'source'), name='unique_resultset_per_user_source'),
        ),
    ]
