# Generated by Django 4.2.28 on 2026-02-17 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0011_resultset_unique_resultset_per_user_source'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='resultset',
            name='unique_resultset_per_user_source',
        ),
    ]
