# Generated by Django 4.2.28 on 2026-02-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0013_resultset_unique_resultset_per_user_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultsetentry',
            name='tied',
            field=models.BooleanField(default=False),
        ),
    ]
