# Generated by Django 4.2.28 on 2026-02-13 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0002_registeredboat'),
        ('members', '0002_alter_emailverificationtoken_id_alter_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='default_boat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_members', to='races.registeredboat'),
        ),
    ]
