# Generated by Django 4.2.28 on 2026-02-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_default_boat'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('date_from', models.DateField(help_text='The first date a race can be added to this league')),
                ('date_to', models.DateField(help_text='The last date a race can be added to this league')),
            ],
        ),
    ]
