# Generated by Django 4.2.28 on 2026-02-13 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_league'),
    ]

    operations = [
        migrations.DeleteModel(
            name='League',
        ),
    ]
