# Generated by Django 4.2.28 on 2026-02-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_delete_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
